server:
  port: 8085

spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8888"
  
  # Kafka Configuration - ENABLED
  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


# Kafka Topics
kafka:
  topic:
    employee-events: employee-events
